### ISSUE TITLE
Production not running

### ISSUE THREAD

**Issue by Iborrezo** [MishUshakov/dialogflow-web-v2#4]
I´m trying to pass the demo to a production server to make some test.
When i run the: 'npm run build' no errors show.
But if i run 'netstat -tnl | grep 8080' to see the services running on that port, nothing is running.
On dev its all OK

**Comment by MishUshakov** [comment]
-_-

Why should it run? It's not an unix executable you are building here.

You do understand, that this is a static assets bundling done by @webpack and you need to upload the build artefacts to a static web server, right?

**Comment by Iborrezo** [comment]
So, i cant publish the dialogflow-web-v2?
I have created my own gateway with my dialogflow logic.
I cant public the index to be able to hit it from outside?
Thanks for the info

**Comment by MishUshakov** [comment]
Of course you can! My demo is hosted right there, using Github Pages!

1. Run `npm run build`
2. Upload your it to a server
3. Serve it with a Web Server (nginx, apache, or just `python -m SimpleHTTPServer 80`)

Or alternatively host it using Cloud Provider like Firebase, Amazon S3 or any other object-storage

You need a static server that can serve your `index.html` and other files to the browsers. That's how websites work.
Since you are here, I assume you know about the technology at least 10x more that my mum, so it shouldn't be a problem for you to upload your app to the `public` folder of your web server, isn't it?
