### ISSUE TITLE
Installing Dialogflow Gateway

### ISSUE THREAD

**Issue by harshitsinghai77** [mishushakov/dialogflow-web-v2#6]
How to add a gateway for Dialogflow? I'm unable to find the gateway key.

**Comment by MishUshakov** [comment]
Hello, dear @harshitsinghai77 thank you for reaching out! The Dialogflow Gateway is a piece of software, that works like a connector between the Web Interface and Dialogflow V2 API. As you may noticed it is no longer available under GitHub. The reason for it is, that I have faced wrong reality and false expectations.

I was always trying to make this Software freely available and open-source. For a good beginnings. I thought, that it will be cool, if anyone can see and contribute to the project and I invited everyone to do so. But some people are so dumb and egoistic, that they don't care about Licensing and Legal aspect of the software, so they violate the License and Terms & Conditions to get their own, personal profits from it. They don't care about copyright holders. They don't care, that any change they make to the software should be published. They don't care, that they can't commercialise it. They just don't give a fuck, because they think if they download the code - it belongs to them and they can do whatever the fuck they want and that no one is going to do anything to them. I certainly don't want the things to work that way. It's a wrong approach. I have lost the power over my work. And there is only one thing I can do right now, to prevent it from happening: I will no longer offer the software. At least not for free and not with the same freedom as before. I will soon introduce new Dialogflow Gateway, that will feature:
- Proprietary source code, that you will only be able to buy from my website
- You will have to give out all of your personal information, so I can fill I lawsuit against you, if you do something wrong
- I will track everything you do with the software and save it on a remote server
- I will block your software, without your permission, just because I wanted it to do so

That's how you wanted things to be? I don't. But it looks like it's the only way to protect us from this wrong world view, where free means "no responsibility". Im very sorry for you, @harshitsinghai77 that you are no longer be able to download the software and use it for good. But, I will promise, that with any of my decision you will end up being happy and you will get the product work for you as well. I hope you will have a nice day! Thank you!

**Comment by mishushakov** [comment]
Ok, things learned
You will be able to Download the new Dialogflow Gateway very soon at https://i.ushakov.co/dialogflow-gateway

Thank you for your patience!

**Comment by prazsolver** [comment]
Where and how to integrate "Dialogflow Gateway", there is not proper instructions on it.
The Dialogflow gateway link in you repo, i.e https://dialogflow-gateway.ushakov.co/ is not working.

So how to integrate and start working on it???

**Comment by mishushakov** [comment]
@prazsolver it's on its way. Don't worry, will be released within a week. Maybe even today. I will then update the repo with the full instructions and setup. You can keep playing with my Agent for now and customise the interface if you want, or just prepare your current application!

Many thanks, sorry to keep you waiting guys, but i want to deliver the best service on the market and it takes time to perfection it.

**Comment by harshitsinghai77** [comment]
Thanks Mishushakov, you're doing a great job. Keep it up. Thanks again for
all your hard work.

Do let me know if you're looking for any collaboration.

Thanks
Harshit Singhai

**Comment by prazsolver** [comment]
Thank you so much mishushakov,

Waiting for your git repo. Make sure u use use the access token of dialogue
flow as you did in v1 and give a proper documentation on connection of
dialogflow and your application, like intents, fulfillment, rest API and so
on.

Thanks in advance.

**Comment by mishushakov** [comment]
@prazsolver @harshitsinghai77 thanks for your understanding. Connecting your Dialogflow V2 Agent will be as easy as pressing on the "Link" button in the Dialogflow Gateway Console. Here a sneak peek:
<img width="1436" alt="Screenshot 2019-03-25 at 13 54 17" src="https://user-images.githubusercontent.com/10400064/54921259-a4cf7180-4f05-11e9-91ac-6539df33dcf4.png">
<img width="1436" alt="Screenshot 2019-03-25 at 13 54 23" src="https://user-images.githubusercontent.com/10400064/54921265-a6993500-4f05-11e9-94b3-7c1eee977746.png">

**Comment by mishushakov** [comment]
Ok, I've updated the Dialogflow for Web v2 and it's docs to support the Dialogflow Gateway. Please follow the steps described in https://github.com/mishushakov/dialogflow-web-v2#getting-started and tell me how it worked. Many thanks

**Comment by prazsolver** [comment]
Thanks dude get back to you after playing on it.

**Comment by prazsolver** [comment]
Hey Mikhail Ushakov,
I am working on your chatbot UI. Pretty well designed.

So how to add Quick Buttons, Cards or Images. Can you share the Custom
payload code for them or add me as a Reviewer/Developer to your Example
dialogflow chatbot.

Help me develop the UI, do u have any personal documentation? please share
if any.

Thanks in advance,

With Regards,
*Praz Solver*

**Comment by mishushakov** [comment]
@prazsolver you can ask Dialogflow to provide you samples and help. It just isn't my part of work, but I'm always happy to help, if there is some issue with the UI or Dialogflow Gateway ;)

**Comment by prazsolver** [comment]
Actually, your app is working pretty well. But only with Text input and
output responses. What i want is how to add Buttons, Cards, Sliders and
other Rich UI to your application. I hope its by adding custom payloads in
the Dialogflow. So can you share some of your JSON template, which you have
used in this example : https://i.ushakov.co/dialogflow-web-v2/

My Question is how to Add rich UI to your application.

You can simply export the Dialogflow and share us.

**Comment by prazsolver** [comment]
Can you help..?

**Comment by malikasinger1** [comment]
what if I wanted to skip the dialogflow gateway, is there any way to put service account directly in the app?

**Comment by malikasinger1** [comment]
or can I install dialogflow gateway on my own server because I dont wanted to involve third party server such as **ushakov.co** in the application flow for security reasons, for sure if I use this server you will be able to track each and every conversation of my customers and this is the world of data and everyone is concerned about data

**Comment by mishushakov** [comment]
Hello,
I understand your concerns and I can assure you, that these are wrong. We do not store or track your conversations or messages. It's too expensive to store your data.

If the goal was to sell your data, we would offer the service for free and pay server bills with the earnings. But as you see, we don't.

The website also mentions this:

<img width="713" alt="Screenshot 2019-06-28 at 12 34 14" src="https://user-images.githubusercontent.com/10400064/60336592-1275b880-99a1-11e9-93f3-caa45ff4d50a.png">

If you are so paranoid about your data, then how can you trust Dialogflow?

You do know, that Dialogflow belongs to Google and their way to earn money is to sell ads, right?
And you do understand, that Dialogflow is offered for free, only because of that? How they still aren't bankrupt?!?

Thanks.

**Comment by Yashashvi-10** [comment]
Is it possible to integrate Emails with dialoglow agent or stand alone emails is the only process?(i.e. using python script, to automate the Emails)

**Comment by mishushakov** [comment]
hey @Yashashvi-10, you can use my repos: https://github.com/mishushakov/dialogflow-sendgrid and https://github.com/mishushakov/dialogflow-inbox
